name: Build Docker And Push
on:
  push:
    branches:
      - master  
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: axon-faucet

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{env.IMAGE_NAME}}:${{ github.sha }}
